apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-app
  labels:
    app: laravel-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: laravel-app
  template:
    metadata:
      labels:
        app: laravel-app
    spec:
      containers:
      - name: laravel-app
        image: felpslaravelstore.azurecr.io/laravel-azure-ci-cd-example:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9000
        name: fastcgi
      imagePullSecrets:
      - name: acr-laravel-creds
---
apiVersion: v1
kind: Service
metadata:
  name: laravel-service
spec:
  selector:
    app: laravel-app
  ports:
  - port: 9000 # Ingress
    targetPort: 9000 # App
    name: fastcgi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fastcgi-config
data:
  SCRIPT_FILENAME: /var/www/html/public/$fastcgi_script_name
  DOCUMENT_ROOT: /var/www/html/public
  SCRIPT_NAME: $fastcgi_script_name
  SERVER-SNIPPET: location / { try_files $uri $uri/ /index.php?$query_string; }
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "FCGI"
    nginx.ingress.kubernetes.io/fastcgi-index: "index.php"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/add-base-url: "true"
    nginx.ingress.kubernetes.io/fastcgi-params-configmap: "fastcgi-config"
  name: ingress-laravel
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: laravel-service
            port:
              name: fastcgi