services:
  app:
    build:
      context: ../
      dockerfile: .docker/app.Dockerfile
      platforms:
        - linux/amd64
    container_name: laravel-app
    networks:
      - laravel-network

  nginx:
    image: nginx:latest
    container_name: laravel-nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge